/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.eventName(async (data) => { ... });
 *   client.server.methodName(args);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/instantcode/app/src/rpc/define.ts
 */

import type { Socket } from "socket.io-client";
import type { RpcError } from "./types.generated";
import type { BrowserSession, PageContext, ElementData, SelectionResult, ScreenshotResult, InjectResult, ConsoleEntry } from "./define";

// === RPCCLIENT INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register handler for 'getPageContext' - called by server */
    getPageContext: (handler: () => Promise<PageContext | RpcError>) => void;
    /** Register handler for 'getSelectedElements' - called by server */
    getSelectedElements: (handler: () => Promise<ElementData[] | RpcError>) => void;
    /** Register handler for 'triggerSelection' - called by server */
    triggerSelection: (handler: (mode: "inspect" | "selector", selector: string | undefined, selectorType: "css" | "xpath" | undefined) => Promise<SelectionResult | RpcError>) => void;
    /** Register handler for 'captureScreenshot' - called by server */
    captureScreenshot: (handler: (type: "viewport" | "element", selector: string | undefined, format: "png" | "jpeg" | undefined, quality: number | undefined) => Promise<ScreenshotResult | RpcError>) => void;
    /** Register handler for 'clearSelection' - called by server */
    clearSelection: (handler: () => Promise<void | RpcError>) => void;
    /** Register handler for 'injectCSS' - called by server */
    injectCSS: (handler: (css: string) => Promise<InjectResult | RpcError>) => void;
    /** Register handler for 'injectJS' - called by server */
    injectJS: (handler: (code: string) => Promise<InjectResult | RpcError>) => void;
    /** Register handler for 'getConsole' - called by server */
    getConsole: (handler: (clear: boolean | undefined) => Promise<ConsoleEntry[] | RpcError>) => void;
    /** Register handler for 'ping' - called by server */
    ping: (handler: () => Promise<string | RpcError>) => void;
    /** Register handler for RPC errors */
    rpcError: (handler: (error: RpcError) => void) => void;
}

/** Methods to call server */
export interface RpcClientServer {
    /** Call server's 'getSessions' method */
    getSessions: (timeout?: number) => Promise<BrowserSession[] | RpcError>;
    /** Call server's 'ping' method */
    ping: (timeout?: number) => Promise<string | RpcError>;
}

/** Client RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup. */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientServer;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.getPageContext(async (data) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.getSessions();
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const handle: RpcClientHandle = {
        getPageContext(handler: () => Promise<PageContext | RpcError>) {
            checkDisposed();
            const listener = async (callback: (result: PageContext | RpcError) => void) => {
                try {
                    const result = await handler();
                    callback(result);
                } catch (error) {
                    console.error('[getPageContext] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('getPageContext', listener);
            unsubscribers.push(() => socket.off('getPageContext', listener));
        },
        getSelectedElements(handler: () => Promise<ElementData[] | RpcError>) {
            checkDisposed();
            const listener = async (callback: (result: ElementData[] | RpcError) => void) => {
                try {
                    const result = await handler();
                    callback(result);
                } catch (error) {
                    console.error('[getSelectedElements] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('getSelectedElements', listener);
            unsubscribers.push(() => socket.off('getSelectedElements', listener));
        },
        triggerSelection(handler: (mode: "inspect" | "selector", selector: string | undefined, selectorType: "css" | "xpath" | undefined) => Promise<SelectionResult | RpcError>) {
            checkDisposed();
            const listener = async (mode: "inspect" | "selector", selector: string | undefined, selectorType: "css" | "xpath" | undefined, callback: (result: SelectionResult | RpcError) => void) => {
                try {
                    const result = await handler(mode, selector, selectorType);
                    callback(result);
                } catch (error) {
                    console.error('[triggerSelection] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('triggerSelection', listener);
            unsubscribers.push(() => socket.off('triggerSelection', listener));
        },
        captureScreenshot(handler: (type: "viewport" | "element", selector: string | undefined, format: "png" | "jpeg" | undefined, quality: number | undefined) => Promise<ScreenshotResult | RpcError>) {
            checkDisposed();
            const listener = async (type: "viewport" | "element", selector: string | undefined, format: "png" | "jpeg" | undefined, quality: number | undefined, callback: (result: ScreenshotResult | RpcError) => void) => {
                try {
                    const result = await handler(type, selector, format, quality);
                    callback(result);
                } catch (error) {
                    console.error('[captureScreenshot] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('captureScreenshot', listener);
            unsubscribers.push(() => socket.off('captureScreenshot', listener));
        },
        clearSelection(handler: () => Promise<void | RpcError>) {
            checkDisposed();
            const listener = async () => {
                try {
                    const result = await handler();
                    if (result && typeof result === 'object' && 'code' in result && 'message' in result) {
                        socket.emit('rpcError', result);
                    }
                } catch (error) {
                    console.error('[clearSelection] Handler error:', error);
                    socket.emit('rpcError', { message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('clearSelection', listener);
            unsubscribers.push(() => socket.off('clearSelection', listener));
        },
        injectCSS(handler: (css: string) => Promise<InjectResult | RpcError>) {
            checkDisposed();
            const listener = async (css: string, callback: (result: InjectResult | RpcError) => void) => {
                try {
                    const result = await handler(css);
                    callback(result);
                } catch (error) {
                    console.error('[injectCSS] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('injectCSS', listener);
            unsubscribers.push(() => socket.off('injectCSS', listener));
        },
        injectJS(handler: (code: string) => Promise<InjectResult | RpcError>) {
            checkDisposed();
            const listener = async (code: string, callback: (result: InjectResult | RpcError) => void) => {
                try {
                    const result = await handler(code);
                    callback(result);
                } catch (error) {
                    console.error('[injectJS] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('injectJS', listener);
            unsubscribers.push(() => socket.off('injectJS', listener));
        },
        getConsole(handler: (clear: boolean | undefined) => Promise<ConsoleEntry[] | RpcError>) {
            checkDisposed();
            const listener = async (clear: boolean | undefined, callback: (result: ConsoleEntry[] | RpcError) => void) => {
                try {
                    const result = await handler(clear);
                    callback(result);
                } catch (error) {
                    console.error('[getConsole] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('getConsole', listener);
            unsubscribers.push(() => socket.off('getConsole', listener));
        },
        ping(handler: () => Promise<string | RpcError>) {
            checkDisposed();
            const listener = async (callback: (result: string | RpcError) => void) => {
                try {
                    const result = await handler();
                    callback(result);
                } catch (error) {
                    console.error('[ping] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('ping', listener);
            unsubscribers.push(() => socket.off('ping', listener));
        },
        rpcError(handler: (error: RpcError) => void) {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            socket.on('rpcError', listener);
            unsubscribers.push(() => socket.off('rpcError', listener));
        }
    };

    const server: RpcClientServer = {
        async getSessions(timeout: number = 5000): Promise<BrowserSession[] | RpcError> {
            try {
                return await socket.timeout(timeout).emitWithAck('getSessions');
            } catch (err) {
                return { message: err instanceof Error ? err.message : String(err), code: 'INTERNAL_ERROR', data: undefined };
            }
        },
        async ping(timeout: number = 5000): Promise<string | RpcError> {
            try {
                return await socket.timeout(timeout).emitWithAck('ping');
            } catch (err) {
                return { message: err instanceof Error ? err.message : String(err), code: 'INTERNAL_ERROR', data: undefined };
            }
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
        }
    };
}
