/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 * 
 * Auto-generated types for the RPC package
 *
 * To regenerate this file, run:
 * bunx socketrpc-gen /Volumes/Data/Projects/instantcode/app/src/rpc/define.ts
 */
/** Function to unsubscribe from an event listener. Call this to clean up the listener. */
export type UnsubscribeFunction = () => void;

/** Represents an error that occurred during an RPC call. */
export interface RpcError {
    /** The error message. */
    message: string;
    /** The error code. */
    code: string;
    /** The error data. */
    data: any;
}

/** Type guard to check if an object is an RpcError. */
export function isRpcError(obj: any): obj is RpcError {
    return !!obj && typeof (obj as RpcError).message === 'string' && typeof (obj as RpcError).code === 'string';
}
